/**
 * Logistics API
 * Logistics API provides services to find and manage entities for logistics
 *
 * OpenAPI spec version: 1.0
 * Contact: vladislavprokopenko1@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateLogistician } from '../model/createLogistician';
import { Logistician } from '../model/logistician';
import { UpdateLogistician } from '../model/updateLogistician';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class LogisticianService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a new Logistician
     * 
     * @param body Logistician object that needs to be added to logistician list
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public logisticianCreate(body: CreateLogistician, observe?: 'body', reportProgress?: boolean): Observable<Logistician>;
    public logisticianCreate(body: CreateLogistician, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Logistician>>;
    public logisticianCreate(body: CreateLogistician, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Logistician>>;
    public logisticianCreate(body: CreateLogistician, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling logisticianCreate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Logistician>('post',`${this.basePath}/logisticians`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete Logistician
     * 
     * @param personalNumber 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public logisticianDelete(personalNumber: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public logisticianDelete(personalNumber: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public logisticianDelete(personalNumber: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public logisticianDelete(personalNumber: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personalNumber === null || personalNumber === undefined) {
            throw new Error('Required parameter personalNumber was null or undefined when calling logisticianDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/logisticians/${encodeURIComponent(String(personalNumber))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find Logistician by id
     * 
     * @param personalNumber 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public logisticianFindById(personalNumber: number, observe?: 'body', reportProgress?: boolean): Observable<Logistician>;
    public logisticianFindById(personalNumber: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Logistician>>;
    public logisticianFindById(personalNumber: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Logistician>>;
    public logisticianFindById(personalNumber: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personalNumber === null || personalNumber === undefined) {
            throw new Error('Required parameter personalNumber was null or undefined when calling logisticianFindById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Logistician>('get',`${this.basePath}/logisticians/${encodeURIComponent(String(personalNumber))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find Logisticians by name and surname
     * 
     * @param name Logistician&#x27;s name
     * @param surname Logistician&#x27;s surname
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public logisticianFindByNameAndSurname(name: string, surname: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Logistician>>;
    public logisticianFindByNameAndSurname(name: string, surname: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Logistician>>>;
    public logisticianFindByNameAndSurname(name: string, surname: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Logistician>>>;
    public logisticianFindByNameAndSurname(name: string, surname: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling logisticianFindByNameAndSurname.');
        }

        if (surname === null || surname === undefined) {
            throw new Error('Required parameter surname was null or undefined when calling logisticianFindByNameAndSurname.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (name !== undefined && name !== null) {
            queryParameters = queryParameters.set('name', <any>name);
        }
        if (surname !== undefined && surname !== null) {
            queryParameters = queryParameters.set('surname', <any>surname);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Logistician>>('get',`${this.basePath}/logisticians/nameAndSurname`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update Logistician
     * 
     * @param body Logistician object that needs to be updated
     * @param personalNumber Logistician personal number
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public logisticianUpdate(body: UpdateLogistician, personalNumber: number, observe?: 'body', reportProgress?: boolean): Observable<Logistician>;
    public logisticianUpdate(body: UpdateLogistician, personalNumber: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Logistician>>;
    public logisticianUpdate(body: UpdateLogistician, personalNumber: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Logistician>>;
    public logisticianUpdate(body: UpdateLogistician, personalNumber: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling logisticianUpdate.');
        }

        if (personalNumber === null || personalNumber === undefined) {
            throw new Error('Required parameter personalNumber was null or undefined when calling logisticianUpdate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Logistician>('patch',`${this.basePath}/logisticians/${encodeURIComponent(String(personalNumber))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find all Logisticians
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public logisticiansFindAll(observe?: 'body', reportProgress?: boolean): Observable<Array<Logistician>>;
    public logisticiansFindAll(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Logistician>>>;
    public logisticiansFindAll(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Logistician>>>;
    public logisticiansFindAll(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Logistician>>('get',`${this.basePath}/logisticians`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
