/**
 * Logistics API
 * Logistics API provides services to find and manage entities for logistics
 *
 * OpenAPI spec version: 1.0
 * Contact: vladislavprokopenko1@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object representing AuthenticationInfo
 */
export interface AuthenticationInfo { 
    id?: number;
    username?: string;
    password?: string;
    role?: AuthenticationInfo.RoleEnum;
}
export namespace AuthenticationInfo {
    export type RoleEnum = 'ROLE_ADMIN' | 'ROLE_LOGISTICIAN' | 'ROLE_DRIVER' | 'ROLE_CUSTOMER';
    export const RoleEnum = {
        ADMIN: 'ROLE_ADMIN' as RoleEnum,
        LOGISTICIAN: 'ROLE_LOGISTICIAN' as RoleEnum,
        DRIVER: 'ROLE_DRIVER' as RoleEnum,
        CUSTOMER: 'ROLE_CUSTOMER' as RoleEnum
    };
}