/**
 * Logistics API
 * Logistics API provides services to find and manage entities for logistics
 *
 * OpenAPI spec version: 1.0
 * Contact: vladislavprokopenko1@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object representing Cargo
 */
export interface Cargo { 
    cargoId?: number;
    orderForCargoId?: number;
    cargoName?: string;
    /**
     * Cargo weight, tons
     */
    weight?: number;
    startCity?: string;
    startState?: string;
    startAddress?: string;
    /**
     * Loading status
     */
    loaded?: Cargo.LoadedEnum;
    finalCity?: string;
    finalState?: string;
    finalAddress?: string;
    /**
     * Unloading status
     */
    unloaded?: Cargo.UnloadedEnum;
    /**
     * Waypoint index based on Google Maps API optimization
     */
    waypointIndex?: number;
    /**
     * Ride distance from start point, km
     */
    rideDistanceFromStartPoint?: number;
    /**
     * Ride duration from start point, minutes
     */
    rideDurationFromStartPoint?: number;
    /**
     * Ride distance from previous point, km
     */
    rideDistanceFromPreviousPoint?: number;
    /**
     * Ride duration from previous point, minutes
     */
    rideDurationFromPreviousPoint?: number;
    expectedCompletionDateTime?: Date;
    realCompletionDateTime?: Date;
}
export namespace Cargo {
    export type LoadedEnum = 'YES' | 'NO';
    export const LoadedEnum = {
        YES: 'YES' as LoadedEnum,
        NO: 'NO' as LoadedEnum
    };
    export type UnloadedEnum = 'YES' | 'NO';
    export const UnloadedEnum = {
        YES: 'YES' as UnloadedEnum,
        NO: 'NO' as UnloadedEnum
    };
}