/**
 * Logistics API
 * Logistics API provides services to find and manage entities for logistics
 *
 * OpenAPI spec version: 1.0
 * Contact: vladislavprokopenko1@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object representing Driver
 */
export interface Driver { 
    personalNumber?: number;
    name?: string;
    surname?: string;
    phone?: string;
    email?: string;
    workExperience?: number;
    workingHoursInCurrentMonth?: number;
    /**
     * rest/driving status
     */
    status?: Driver.StatusEnum;
    /**
     * Busy status
     */
    busy?: Driver.BusyEnum;
    currentCity?: string;
    currentState?: string;
    currentTruckNumber?: string;
    currentOrderId?: number;
    /**
     * Order acceptance
     */
    orderAcceptance?: Driver.OrderAcceptanceEnum;
    driverComment?: string;
}
export namespace Driver {
    export type StatusEnum = 'REST' | 'DRIVING';
    export const StatusEnum = {
        REST: 'REST' as StatusEnum,
        DRIVING: 'DRIVING' as StatusEnum
    };
    export type BusyEnum = 'YES' | 'NO';
    export const BusyEnum = {
        YES: 'YES' as BusyEnum,
        NO: 'NO' as BusyEnum
    };
    export type OrderAcceptanceEnum = 'YES' | 'NO';
    export const OrderAcceptanceEnum = {
        YES: 'YES' as OrderAcceptanceEnum,
        NO: 'NO' as OrderAcceptanceEnum
    };
}