/**
 * Logistics API
 * Logistics API provides services to find and manage entities for logistics
 *
 * OpenAPI spec version: 1.0
 * Contact: vladislavprokopenko1@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object representing Order
 */
export interface Order { 
    orderId?: number;
    numberOfCargos?: number;
    orderCustomerId?: number;
    category?: string;
    /**
     * Total order weight, tons
     */
    weight?: number;
    status?: Order.StatusEnum;
    startDateTime?: Date;
    limitDateTime?: Date;
    assignedTruckNumber?: string;
    numberOfAssignedDrivers?: number;
}
export namespace Order {
    export type StatusEnum = 'NEW' | 'EXPECT_DRIVERS_CONFIRMATION' | 'CONFIRMED' | 'DECLINED_BY_DRIVERS' | 'ON_ROAD' | 'COMPLETED';
    export const StatusEnum = {
        NEW: 'NEW' as StatusEnum,
        EXPECTDRIVERSCONFIRMATION: 'EXPECT_DRIVERS_CONFIRMATION' as StatusEnum,
        CONFIRMED: 'CONFIRMED' as StatusEnum,
        DECLINEDBYDRIVERS: 'DECLINED_BY_DRIVERS' as StatusEnum,
        ONROAD: 'ON_ROAD' as StatusEnum,
        COMPLETED: 'COMPLETED' as StatusEnum
    };
}