/**
 * Logistics API
 * Logistics API provides services to find and manage entities for logistics
 *
 * OpenAPI spec version: 1.0
 * Contact: vladislavprokopenko1@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object representing Order acceptance request for Driver
 */
export interface UpdateDriverOrderAcceptance { 
    /**
     * Order acceptance
     */
    orderAcceptance?: UpdateDriverOrderAcceptance.OrderAcceptanceEnum;
}
export namespace UpdateDriverOrderAcceptance {
    export type OrderAcceptanceEnum = 'YES' | 'NO';
    export const OrderAcceptanceEnum = {
        YES: 'YES' as OrderAcceptanceEnum,
        NO: 'NO' as OrderAcceptanceEnum
    };
}