/**
 * Logistics API
 * Logistics API provides services to find and manage entities for logistics
 *
 * OpenAPI spec version: 1.0
 * Contact: vladislavprokopenko1@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object representing Cargo updating by Driver
 */
export interface UpdateCargoByDriver { 
    /**
     * Loading status
     */
    loaded?: UpdateCargoByDriver.LoadedEnum;
    /**
     * Unloading status
     */
    unloaded?: UpdateCargoByDriver.UnloadedEnum;
}
export namespace UpdateCargoByDriver {
    export type LoadedEnum = 'YES' | 'NO';
    export const LoadedEnum = {
        YES: 'YES' as LoadedEnum,
        NO: 'NO' as LoadedEnum
    };
    export type UnloadedEnum = 'YES' | 'NO';
    export const UnloadedEnum = {
        YES: 'YES' as UnloadedEnum,
        NO: 'NO' as UnloadedEnum
    };
}